@baseUrl = http://localhost:8080

GET {{baseUrl}}/api/players

###
GET {{baseUrl}}/api/players/2

###
GET {{baseUrl}}/api/players/999

###
GET {{baseUrl}}/api/players?club=Arsenal

###
GET {{baseUrl}}/api/players?position=Forward

###
GET {{baseUrl}}/api/players?club=Arsenal&position=Forward

###
GET {{baseUrl}}/api/matches

###
GET {{baseUrl}}/api/matches/1

###
GET {{baseUrl}}/api/matches/999

###
GET {{baseUrl}}/api/matches?club=Arsenal

###
GET {{baseUrl}}/api/matches?matchweek=1

###
GET {{baseUrl}}/api/matches?club=Arsenal&matchweek=1

###
GET {{baseUrl}}/api/matches?status=FINISHED

###
GET {{baseUrl}}/api/matches?matchweek=0

###
GET {{baseUrl}}/api/standings

###
GET {{baseUrl}}/api/standings?limit=5

###
GET {{baseUrl}}/api/standings/1

###
GET {{baseUrl}}/api/standings?limit=0
