-- Accounts are independent of football players, memberships and seasons.
-- A nullable password allows a later Google identity to share this same account.
CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    display_name VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255),
    role VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT accounts_email_unique UNIQUE (email),
    CHECK (role IN ('USER', 'ADMIN'))
);

-- A provider subject identifies a Google identity; email never links accounts implicitly.
CREATE TABLE IF NOT EXISTS account_identities (
    provider VARCHAR(16) NOT NULL,
    subject_id VARCHAR(255) NOT NULL,
    account_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT account_identities_pk PRIMARY KEY (provider, subject_id),
    CONSTRAINT account_identities_account_fk FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- Spring Session JDBC's standard tables, idempotent local H2 DDL.
-- MySQL requires a reviewed migration (its CREATE INDEX syntax differs).
CREATE TABLE IF NOT EXISTS SPRING_SESSION (
    PRIMARY_ID CHAR(36) NOT NULL,
    SESSION_ID CHAR(36) NOT NULL,
    CREATION_TIME BIGINT NOT NULL,
    LAST_ACCESS_TIME BIGINT NOT NULL,
    MAX_INACTIVE_INTERVAL INT NOT NULL,
    EXPIRY_TIME BIGINT NOT NULL,
    PRINCIPAL_NAME VARCHAR(254),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID),
    CONSTRAINT SPRING_SESSION_IX1 UNIQUE (SESSION_ID)
);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX IF NOT EXISTS SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);
CREATE TABLE IF NOT EXISTS SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
    ATTRIBUTE_BYTES BLOB NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION(PRIMARY_ID) ON DELETE CASCADE
);
